[package]
name = "chip-8"
version = "0.1.0"
authors = ["Jake Carrington <jake.ethan.carrington@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
glium = "*"
hex = "*"
rand = "*"